server:
  host: 0.0.0.0
  port: 8085
  servlet:
    context-path: /api

spring:
  application:
    name: RAG-Service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # 数据源配置
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/kb_platform
    username: postgres
    password:  # 空密码
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: RAG-HikariCP

# MybatisPlus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.luanjining.rag.entity
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: INPUT
      field-strategy: NOT_EMPTY
      db-type: POSTGRESQL

# RAG配置
rag:
  dify:
    authorization-dataset: Bearer dataset-juR2DRl8alE1eBvQmvJ6KiVs
    authorization-app: Bearer app-9u1tQG9ZjsmY51SWZDBn9tyD
    user-id: 202521081036@std.uestc.edu.cn
    base-url: https://api.dify.ai/v1
    dataset-id: bafabbc4-0093-49ec-94a7-71a1e786105d

# MinIO配置
minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: rag-documents

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

# 日志配置
logging:
  level:
    com.luanjining: DEBUG
    org.springdoc: DEBUG  # 添加这行来查看SpringDoc日志
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"