server:
  port: 8085
  servlet:
    context-path: /api

spring:
  application:
    name: RAG-Service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # 数据源配置 - 确认密码为空
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/kb_platform
    username: postgres
    password:  # 空密码




# RAG配置
rag:
  dify:
    authorization-dataset: Bearer dataset-juR2DRl8alE1eBvQmvJ6KiVs
    authorization-app: Bearer app-9u1tQG9ZjsmY51SWZDBn9tyD
    user-id: 202521081036@std.uestc.edu.cn
    base-url: https://api.dify.ai/v1
    dataset-id: bafabbc4-0093-49ec-94a7-71a1e786105d




logging:
  level:
    com.luanjining: DEBUG
    org.springframework.web: INFO
    # 数据库相关日志
    com.luanjining.mapper: DEBUG
    druid.sql: DEBUG