# application.yml
server:
  port: 8085
  servlet:
    context-path: /api

spring:
  application:
    name: RAG-Service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # 数据源配置
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/kb_platform
    username: postgres
    password:  # 空密码
    # 连接池配置
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: RAG-HikariCP

# MybatisPlus配置
mybatis-plus:
  # 配置mapper的扫描路径
  mapper-locations: classpath*:/mapper/**/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.luanjining.rag.entity
  # 配置
  configuration:
    # 是否开启自动驼峰命名规则映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    # 数据库相关配置
    db-config:
      # 主键类型
      id-type: INPUT
      # 字段策略
      field-strategy: NOT_EMPTY
      # 数据库类型
      db-type: POSTGRESQL

# RAG配置
rag:
  dify:
    authorization-dataset: Bearer dataset-juR2DRl8alE1eBvQmvJ6KiVs
    authorization-app: Bearer app-9u1tQG9ZjsmY51SWZDBn9tyD
    user-id: 202521081036@std.uestc.edu.cn
    base-url: https://api.dify.ai/v1
    dataset-id: bafabbc4-0093-49ec-94a7-71a1e786105d

# MinIO配置
minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: rag-documents

springdoc:
  api-docs:
    path: /api/v3/api-docs  # 加上 /api 前缀
  swagger-ui:
    path: /api/swagger-ui.html  # 加上 /api 前缀


# 日志配置
logging:
  level:
    com.luanjining: DEBUG
    com.luanjining.rag.mapper: DEBUG
    com.baomidou.mybatisplus: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"